### ISSUE TITLE
Cannot build on windows 10

### ISSUE THREAD

**Issue by alexmario74** [inotify-rs/inotify-sys#11]
Hello, 
have an issue building on Windows machine.

Here is the error:

```
$ cargo test
   Updating crates.io index
   Compiling libc v0.2.48
   Compiling inotify-sys v0.1.4-dev (C:\WORK\SOC\inotify-sys)
  --> src\lib.rs:58:37
   |
58 | pub const IN_CLOEXEC: c_int = libc::O_CLOEXEC;
   |                                     ^^^^^^^^^ not found in `libc`
error[E0425]: cannot find value `O_NONBLOCK` in module `libc`
  --> src\lib.rs:69:38
   |
69 | pub const IN_NONBLOCK: c_int = libc::O_NONBLOCK;
   |                                      ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `O_CLOEXEC` in module `libc`
  --> src\lib.rs:58:37
   |
58 | pub const IN_CLOEXEC: c_int = libc::O_CLOEXEC;
   |                                     ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `O_NONBLOCK` in module `libc`
  --> src\lib.rs:69:38
   |
69 | pub const IN_NONBLOCK: c_int = libc::O_NONBLOCK;
   |                                      ^^^^^^^^^^ not found in `libc`

error: aborting due to 2 previous errors
```

My toolchain:

```
active toolchain
----------------

nightly-2019-01-14-x86_64-pc-windows-msvc (default)
rustc 1.33.0-nightly (2fadb0a16 2019-01-13)
```

I downloaded the `libc` and I build it without problems.
I have no issue building on linux.

Thanks in advance for help.

Mario

**Comment by hannobraun** [comment]
Hi @alexmario74. inotify is a Linux API which is not available on Windows (there's Windows Subsystem for Linux, which might have a version of inotify, but I know nothing about that). Windows has its own API to watch file system changes, but I know nothing about that either.

You can probably use [notify](https://github.com/passcod/notify), which is a cross-platform library that uses inotify on Linux and other APIs on other platforms.

**Comment by alexmario74** [comment]
Hi @hannobraun , thanks for the response.

I have inotify-sys as a dependency I have in my project, the target platform is Linux, but it would be good to be able to build and run the tests on windows too, just for development.

Thanks anyway, I think I can close this issue then.

**Comment by hannobraun** [comment]
Well, you should be able to use Windows to cross-compile for Linux, by passing the right `--target` to Cargo. Your libc compilation issues should disappear then. You can't run the tests though, as that would require the presence of inotify (unless maybe you use Windows Subsystem for Linux, as I said in my previous comment).

inotify-sys just contains bindings to the native inotify, so without inotify support from the Linux kernel, the library itself can do nothing.

**Comment by alexmario74** [comment]
Thanks again for your suggestion, unfortunately I'm not able to perform a cross-compile build on Windows.

The linux target haven't a rustc available... :(
